name: pert_ldm
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - et_xmlfile=1.1.0=py312h06a4308_1
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.23.0=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_1
  - matplotlib-base=3.9.2=py312hbfdbfaf_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.10=py312h5eee18b_0
  - mkl_random=1.2.7=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py312h5eee18b_0
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.7=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.4.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - qt-main=5.15.2=hb6262e9_11
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - seaborn=0.13.2=py312h06a4308_2
  - setuptools=75.1.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.1=py312_cu124
  - torchtriton=3.0.0=py312
  - torchvision=0.19.1=py312_cu124
  - traitlets=5.14.3=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - alabaster==1.0.0
      - altair==5.5.0
      - anndata==0.11.4
      - annotated-types==0.7.0
      - anyio==4.9.0
      - array-api-compat==1.12.0
      - asttokens==2.4.1
      - attrs==25.1.0
      - babel==2.17.0
      - bio==1.8.0
      - biopython==1.85
      - biothings-client==0.4.1
      - blinker==1.9.0
      - brokenaxes==0.6.2
      - cachetools==5.5.2
      - cattrs==24.1.2
      - charset-normalizer==3.3.2
      - chembl-webresource-client==0.10.9
      - chemprop==1.5.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmappy==4.0.1
      - comm==0.2.2
      - debugpy==1.8.7
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - docutils==0.21.2
      - easydict==1.13
      - einops==0.8.1
      - executing==2.1.0
      - flask==3.1.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gprofiler-official==1.0.0
      - gtfparse==2.5.0
      - h11==0.16.0
      - h5py==3.12.1
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - hyperopt==0.2.7
      - imagesize==1.4.1
      - ipykernel==6.29.5
      - ipython==8.29.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - joblib==1.4.2
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - legacy-api-wrap==1.4.1
      - littleutils==0.2.4
      - llvmlite==0.44.0
      - matplotlib-inline==0.1.7
      - multidict==6.1.0
      - mygene==3.2.2
      - mypy-extensions==1.0.0
      - narwhals==1.35.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - numba==0.61.2
      - numpy==1.26.4
      - ogb==1.3.6
      - outdated==0.2.2
      - packaging==25.0
      - pandas==2.1.3
      - pandas-flavor==0.6.0
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - plotly==6.2.0
      - polars==0.20.31
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==5.29.4
      - psutil==6.1.0
      - psycopg2==2.9.10
      - ptyprocess==0.7.0
      - pubchempy==1.0.4
      - pure-eval==0.2.3
      - py4j==0.10.9.9
      - pyarrow==14.0.2
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydeck==0.9.1
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyzmq==26.2.0
      - rdkit==2023.9.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-cache==1.2.1
      - roman-numerals-py==3.1.0
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scanpy==1.11.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentry-sdk==2.26.1
      - session-info2==0.1.2
      - setproctitle==1.3.5
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - streamlit==1.44.1
      - tenacity==9.1.2
      - tensorboardx==2.6.2.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu124
      - torchinfo==1.8.0
      - tornado==6.4.1
      - tqdm==4.67.1
      - transformers==4.51.3
      - typed-argument-parser==1.10.1
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - umap-learn==0.5.7
      - url-normalize==1.4.3
      - wandb==0.19.9
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - xarray==2025.1.2
      - yarl==1.18.3
prefix: /home/$USER/anaconda3/envs/pert_ldm
